// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: test.sql

package db

import (
	"context"
)

const createTest = `-- name: CreateTest :one
INSERT INTO test (
  note
) VALUES (
  $1
) RETURNING id, note, created_at
`

func (q *Queries) CreateTest(ctx context.Context, note string) (Test, error) {
	row := q.db.QueryRow(ctx, createTest, note)
	var i Test
	err := row.Scan(&i.ID, &i.Note, &i.CreatedAt)
	return i, err
}
