services:
  pgmodeler:
    image: 'apazga/docker-pgmodeler'
    environment:
      DISPLAY: $DISPLAY
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
      XDG_RUNTIME_DIR: $XDG_RUNTIME_DIR
      PULSE_SERVER: $PULSE_SERVER
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /mnt/wslg:/mnt/wslg
      - /work/my/golang/course/backend-master-class-go-postgre-k8s/postgres/data/:/models/
      - /work/my/golang/course/backend-master-class-go-postgre-k8s/postgres/pgmodeler/config/:/root/.config/pgmodeler-1.0
