// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: service_simle_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_simle_bank_proto protoreflect.FileDescriptor

const file_service_simle_bank_proto_rawDesc = "" +
	"\n" +
	"\x18service_simle_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a\x14rpc_login_user.proto\x1a\x16rpc_verify_email.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xd2\x04\n" +
	"\n" +
	"SimpleBank\x12\x8d\x01\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"P\x92A3\x12\x0fCreate new user\x1a Use this API to crate a new user\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12\xa2\x01\n" +
	"\tLoginUser\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"h\x92AL\x12\n" +
	"Login user\x1a>Use this API to login user and get access token & refres token\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12\x84\x01\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"G\x92A*\x12\vUpdate user\x1a\x1bUse this API to update user\x82\xd3\xe4\x93\x02\x14:\x01*2\x0f/v1/update_user\x12\x87\x01\n" +
	"\vVerifyEmail\x12\x16.pb.VerifyEamilRequest\x1a\x17.pb.VerifyEamilResponse\"G\x92A,\x12\fVerify email\x1a\x1cUse this API to verify email\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/verify_emailBs\x92AK\x12I\n" +
	"\x0fSimple Bank API\"1\n" +
	"\x11Test bank project\x12\n" +
	"http://url\x1a\x10none@example.com2\x031.2Z#github.com/matodrobec/simplebank/pbb\x06proto3"

var file_service_simle_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),   // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),    // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),   // 2: pb.UpdateUserRequest
	(*VerifyEamilRequest)(nil),  // 3: pb.VerifyEamilRequest
	(*CreateUserResponse)(nil),  // 4: pb.CreateUserResponse
	(*LoginUserResponse)(nil),   // 5: pb.LoginUserResponse
	(*UpdateUserResponse)(nil),  // 6: pb.UpdateUserResponse
	(*VerifyEamilResponse)(nil), // 7: pb.VerifyEamilResponse
}
var file_service_simle_bank_proto_depIdxs = []int32{
	0, // 0: pb.SimpleBank.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.SimpleBank.LoginUser:input_type -> pb.LoginUserRequest
	2, // 2: pb.SimpleBank.UpdateUser:input_type -> pb.UpdateUserRequest
	3, // 3: pb.SimpleBank.VerifyEmail:input_type -> pb.VerifyEamilRequest
	4, // 4: pb.SimpleBank.CreateUser:output_type -> pb.CreateUserResponse
	5, // 5: pb.SimpleBank.LoginUser:output_type -> pb.LoginUserResponse
	6, // 6: pb.SimpleBank.UpdateUser:output_type -> pb.UpdateUserResponse
	7, // 7: pb.SimpleBank.VerifyEmail:output_type -> pb.VerifyEamilResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_simle_bank_proto_init() }
func file_service_simle_bank_proto_init() {
	if File_service_simle_bank_proto != nil {
		return
	}
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	file_rpc_login_user_proto_init()
	file_rpc_verify_email_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_simle_bank_proto_rawDesc), len(file_service_simle_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_simle_bank_proto_goTypes,
		DependencyIndexes: file_service_simle_bank_proto_depIdxs,
	}.Build()
	File_service_simle_bank_proto = out.File
	file_service_simle_bank_proto_goTypes = nil
	file_service_simle_bank_proto_depIdxs = nil
}
