# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: Build image
    runs-on: self-hosted

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4


    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
    #   with:
    #     role-to-assume: arn:aws:iam::123456789012:role/my-github-actions-role
    #     aws-region: eu-central-1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Load secrets and save to app.env
      run: |
        aws secretsmanager get-secret-value --secret-id "prod/simple_bank" --query SecretString --output text | jq 'to_entries | map("\(.key)=\(.value)") | .[]' -r > app.env.prod
        cp ./app.env.dist ./app.env
        ./bin/merge-env.sh

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -f ./docker/images/app/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG